### ISSUE TITLE
สอบถามเรื่อง Modules กับ Components ครับ

### ISSUE THREAD

**Issue by playcodebyflapjack** [nutbutterfly/youtube-training-angular-frontend#1]
ระหว่าง Modules กับ Components มีความแตกต่างอย่างไรครับ
จะมองว่า 1 หน้า คือ 1 Components  (ตัวอย่างใน ep5-ep6)
หรือ จะมองว่า 1 หน้า คือ 1 Modules ดีครับ
รบกวนช่วยอธิบายทีน่ะครับ

<img src="https://user-images.githubusercontent.com/6084576/110939817-93890500-8368-11eb-867a-48507e2f49aa.png" width="80" height="95">

**Comment by playcodebyflapjack** [comment]
ได้รับคำตอบจาก[ลิงก์](https://youtu.be/EHW64qm_OQI?t=1810)แล้วครับ 
ขอบคุณมากครับ
<img src="https://stickershop.line-scdn.net/stickershop/v1/sticker/92409845/iPhone/sticker@2x.png" width="100" height="100" >

**Comment by nutbutterfly** [comment]
> ได้รับคำตอบจาก[ลิงก์](https://youtu.be/EHW64qm_OQI?t=1810)แล้วครับ
> ขอบคุณมากครับ
> <img alt="" width="100" height="100" src="https://camo.githubusercontent.com/a02527dabdd6931ef8f14330760910e3b9267ca0505d25208f2405a92d6035d7/68747470733a2f2f737469636b657273686f702e6c696e652d7363646e2e6e65742f737469636b657273686f702f76312f737469636b65722f39323430393834352f6950686f6e652f737469636b65724032782e706e67">

ขอบคุณครับผม :)
